/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableArray, NSString, PBXCheapReusableSubstring;

@interface XCCharStream : NSObject
{
    void *_buff;
    BOOL _isAtBOL;
    BOOL _isAtColumnZero;
    BOOL _BOLIsKnown;
    BOOL _SeenOneCharAtBOL;
    BOOL _SeenWhitespaceAtBOL;
    NSString *_realString;
    PBXCheapReusableSubstring *_cheapString;
    NSMutableArray *_savedTokens;
}

+ (void)initialize;
- (id)initWithString:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (void)setString:(id)fp8;
- (id)string;
- (unsigned int)length;
- (unsigned int)location;
- (void)setLocation:(unsigned int)fp8;
- (unsigned short)nextChar;
- (unsigned short)nextCharSkippingWhitespace;
- (void)_computeBOL;
- (BOOL)isAtBOL;
- (BOOL)isAtColumnZero;
- (unsigned short)peekChar;
- (unsigned short)peekCharSkippingWhitespace;
- (unsigned int)peekCharacterInSet:(id)fp8;
- (unsigned int)locationOfNewlineFrom:(unsigned int)fp8 searchBackwards:(BOOL)fp12;
- (id)stringWithRange:(struct _NSRange)fp8;
- (void)saveToken:(id)fp8;
- (BOOL)hasSavedTokens;
- (id)savedToken;

@end

