/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableArray;

@interface XCSourceModelItem : NSObject
{
    struct _NSRange _relativeLocation;
    unsigned int _colorId:16;
    unsigned int _dirty:1;
    unsigned int _isBlock:1;
    unsigned int _ignoreToken:1;
    unsigned int _inheritsColor:1;
    unsigned int _isIdentifier:1;
    unsigned int _isSimpleToken:1;
    unsigned int _isVolatile:1;
    unsigned int _needToDirtyRightEdges:1;
    int _langId;
    int _token;
    XCSourceModelItem *_parent;
    NSMutableArray *_children;
}

+ (id)sourceModelItemWithRange:(struct _NSRange)fp8 language:(int)fp16 token:(int)fp20 color:(short)fp24;
- (id)initWithRange:(struct _NSRange)fp8 language:(int)fp16 token:(int)fp20 color:(short)fp24;
- (void)dealloc;
- (id)innerDescription:(id)fp8 showSelf:(BOOL)fp12;
- (id)description;
- (id)diffableDescription;
- (id)simpleDescription;
- (id)contextArray;
- (id)dumpContext;
- (void)validate;
- (void)dirtyRelativeRange:(struct _NSRange)fp8 changeInLength:(int)fp16;
- (void)dirtyRange:(struct _NSRange)fp8 changeInLength:(int)fp16;
- (BOOL)isBlock;
- (void)setIsBlock:(BOOL)fp8;
- (int)blockDepth;
- (id)enclosingBlock;
- (struct _NSRange)range;
- (void)setRange:(struct _NSRange)fp8;
- (void)offsetBy:(int)fp8;
- (struct _NSRange)innerRange;
- (void)setColorId:(short)fp8;
- (short)colorId;
- (BOOL)isIdentifier;
- (int)langId;
- (void)setToken:(int)fp8;
- (int)token;
- (void)setDirty:(BOOL)fp8;
- (BOOL)dirty;
- (void)setIgnoreToken:(BOOL)fp8;
- (BOOL)ignoreToken;
- (void)setInheritsColor:(BOOL)fp8;
- (BOOL)inheritsColor;
- (void)setIsSimpleToken:(BOOL)fp8;
- (BOOL)isSimpleToken;
- (void)setNeedToDirtyRightEdges:(BOOL)fp8;
- (BOOL)needToDirtyRightEdges;
- (void)setVolatile:(BOOL)fp8;
- (BOOL)isVolatile;
- (id)parent;
- (void)setParent:(id)fp8;
- (void)assignParents:(id)fp8;
- (void)addChild:(id)fp8;
- (void)addChildren:(id)fp8;
- (unsigned int)numberOfChildren;
- (id)children;
- (unsigned int)indexOfChildBeforeLocation:(unsigned int)fp8;
- (unsigned int)indexOfChildAfterLocation:(unsigned int)fp8;
- (unsigned int)indexOfChildAtLocation:(unsigned int)fp8;
- (id)_childEnclosingLocation:(unsigned int)fp8;
- (id)childEnclosingLocation:(unsigned int)fp8;
- (BOOL)isAncestorOf:(id)fp8;
- (id)previousItem;
- (id)nextItem;

@end

